name: verify
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code base
      uses: actions/checkout@v2.3.1

    - name: Prepare Maven artifact cache
      uses: actions/cache@v2.0.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8

    - name: setup-maven-settings
      uses: s4u/maven-settings-action@v2.1.0
      with:
        servers: '[{"id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_PASSWORD }}"}]'

    - name: Prepare gpg environment 
      uses: crazy-max/ghaction-import-gpg@v2.1.1
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Check gpg environment
      run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

    - name: Build project with Maven
      run: mvn -B -Possrh deploy

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1.0.10
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        cname: spring-hateoas-siren.ingogriebsch.de
        full_commit_message: ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/generated-docs
        user_email: 'github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
